import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createAtmosphere} from './atmosphere.js';
import {mountainMist,addMountainVegetation} from './mountain-atmosphere.js';

export function createMountainChapter(renderer,water){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#adbec4');scene.fog=new THREE.FogExp2('#91a8ad',.0065);
 const camera=new THREE.PerspectiveCamera(40,2,.1,900),atmosphere=createAtmosphere(scene),mist=mountainMist(scene);
 scene.add(new THREE.HemisphereLight(0xd8e6e8,0x243638,1.35));
 const sun=new THREE.DirectionalLight(0xffecd5,2.7);sun.position.set(12,35,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:25,bottom:-20,near:1,far:110});sun.shadow.normalBias=.055;scene.add(sun);
 const hud=document.createElement('section');hud.id='mountain-ui';hud.hidden=true;
 hud.innerHTML=`<div class="chapter-label">III · WHERE MEMORY TAKES WING</div><p id="mountain-line" aria-live="polite">Even in stillness, something remembers how to fly.</p><div class="mountain-actions"><button id="wake-butterfly">Wake the Butterfly</button><button data-perch="Veil" hidden>Rest on the Veil</button><button data-perch="Branch" hidden>Rest on the Branch</button><button data-perch="Leopard" hidden>Rest on the Leopard</button><button id="mountain-orbit">Orbit: On</button><button id="mountain-reset">Reset View</button><button id="mountain-continue" hidden>Follow the Silent Sun</button><button id="mountain-return">Return to the Grove</button></div><small id="mountain-hint">Click a butterfly · Drag to look around · Scroll to move closer</small><div id="perch-progress" aria-label="Remembered resting places"></div>`;
 document.body.append(hud);const q=s=>hud.querySelector(s),line=q('#mountain-line');
 let loaded=false,active=false,promise,error,model,main,anchors={},state='resting',anim=0,localTime=0,orbit=true,base=0,flightStart=new THREE.Vector3(),landing='',curve;
 const visited=new Set(),butterflies=[],markers=[],ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let yaw=.25,pitch=0,distance=36,smoothYaw=.25,smoothPitch=0,smoothDistance=36,drag=null,moved=false;
 function ui(){q('#mountain-continue').hidden=visited.size<3;q('#wake-butterfly').hidden=state==='flying'||state==='landing';q('#wake-butterfly').textContent=visited.size?'Let It Fly Again':'Wake the Butterfly';hud.querySelectorAll('[data-perch]').forEach(b=>{b.hidden=state!=='flying';b.classList.toggle('visited',visited.has(b.dataset.perch));});q('#perch-progress').textContent=visited.size?`${visited.size} / 3 resting places remembered`:'';markers.forEach(m=>m.visible=state==='flying');}
 function load(){if(promise)return promise;promise=new GLTFLoader().loadAsync('./models/jiuge_mountain.glb').then(g=>{
  model=g.scene;scene.add(model);const seen=new Set();model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of [].concat(o.material)){if(seen.has(m))continue;seen.add(m);if(m.userData.web_color_multiplier)m.color.multiply(new THREE.Color(...m.userData.web_color_multiplier));m.roughness=Math.max(.65,m.roughness??.8);if(m.map)m.map.anisotropy=4;}}});
  const nearPeak=model.getObjectByName('Mountain_Peak_0');if(nearPeak)nearPeak.scale.x*=1.45;
  addMountainVegetation(model,scene);
  for(const k of ['Veil','Branch','Leopard']){const a=model.getObjectByName('Perch_'+k);if(!a)throw Error('Missing perch '+k);anchors[k]=a.getWorldPosition(new THREE.Vector3());const marker=new THREE.Mesh(new THREE.SphereGeometry(.17,16,12),new THREE.MeshBasicMaterial({color:0xffd096,transparent:true,opacity:.65}));marker.position.copy(anchors[k]).add(new THREE.Vector3(0,.3,0));marker.userData.perch=k;marker.visible=false;scene.add(marker);markers.push(marker);}
  const rider=model.getObjectByName('Veiled_Rider');base=new THREE.Box3().setFromObject(rider).min.y;
  const proto=model.getObjectByName('Butterfly_Template');if(!proto)throw Error('Missing butterfly rig');proto.visible=false;
  for(let i=0;i<7;i++){const b=proto.clone(true);b.visible=true;b.position.copy(anchors[['Veil','Branch','Leopard'][i%3]]);if(i>0)b.position.add(new THREE.Vector3(Math.sin(i*2.4)*.8,.2+(i%3)*.2,.2));b.scale.setScalar(i===0?.9:.42);b.userData.wings=[b.getObjectByName('Wing_Left_Pivot'),b.getObjectByName('Wing_Right_Pivot')];b.userData.rest=b.position.clone();b.userData.phase=i*1.9;b.traverse(o=>{if(o.isMesh){o.castShadow=false;for(const m of [].concat(o.material))m.side=THREE.DoubleSide;}});scene.add(b);butterflies.push(b);}main=butterflies[0];
  curve=new THREE.CatmullRomCurve3([anchors.Veil.clone().add(new THREE.Vector3(0,1,2)),anchors.Veil.clone().add(new THREE.Vector3(3,2,3)),anchors.Branch.clone().add(new THREE.Vector3(2,2,3)),anchors.Branch.clone().add(new THREE.Vector3(-1,1,3)),anchors.Leopard.clone().add(new THREE.Vector3(2,2,3))],true,'catmullrom',.35);
  loaded=true;ui();return true;
 }).catch(e=>{error=e;promise=null;console.error('Chapter III:',e);return false;});return promise;}
 function wake(){if(!active||!loaded||!['resting','perched'].includes(state))return;flightStart.copy(main.position);anim=0;state='flying';line.textContent='Choose where this small memory will rest.';ui();}
 function land(k){if(state!=='flying')return;flightStart.copy(main.position);landing=k;anim=0;state='landing';line.textContent='A fleeting presence finds its place.';ui();}
 q('#wake-butterfly').onclick=wake;hud.querySelectorAll('[data-perch]').forEach(b=>b.onclick=()=>land(b.dataset.perch));q('#mountain-orbit').onclick=()=>{orbit=!orbit;q('#mountain-orbit').textContent='Orbit: '+(orbit?'On':'Off');};q('#mountain-reset').onclick=()=>{yaw=.25;pitch=0;distance=36;};
 renderer.domElement.addEventListener('pointerdown',e=>{if(!active)return;drag={x:e.clientX,y:e.clientY,yaw,pitch};moved=false;renderer.domElement.setPointerCapture(e.pointerId);});
 renderer.domElement.addEventListener('pointermove',e=>{if(!active||!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)moved=true;yaw=THREE.MathUtils.clamp(drag.yaw-dx*.002,-.12,.6);pitch=THREE.MathUtils.clamp(drag.pitch+dy*.012,-2,4);});
 renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);
 renderer.domElement.addEventListener('wheel',e=>{if(!active)return;e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.013,27,43);},{passive:false});
 renderer.domElement.addEventListener('click',e=>{if(!active||!loaded||moved)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);if(state==='flying'){const hit=ray.intersectObjects(markers)[0];if(hit)land(hit.object.userData.perch);}else if(ray.intersectObjects(butterflies,true).length)wake();});
 function update(dt,time){if(!active||!loaded)return;localTime+=dt;anim+=dt;atmosphere.update(time);mist.update(time);smoothYaw=THREE.MathUtils.damp(smoothYaw,yaw,3,dt);smoothPitch=THREE.MathUtils.damp(smoothPitch,pitch,3,dt);smoothDistance=THREE.MathUtils.damp(smoothDistance,distance,3,dt);
  const a=smoothYaw+(orbit?Math.sin(localTime*.12)*.065:0);camera.aspect=renderer.domElement.clientWidth/renderer.domElement.clientHeight;camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(30))/camera.aspect));camera.updateProjectionMatrix();camera.position.set(1+Math.sin(a)*smoothDistance,base+11+smoothPitch,Math.cos(a)*smoothDistance);camera.lookAt(1,base+6.5,0);
  if(state==='flying'){const p=curve.getPointAt((anim*.075)%1),t=THREE.MathUtils.smoothstep(anim,0,2);main.position.lerpVectors(flightStart,p,t);main.rotation.set(.1,Math.sin(anim*.6)*.6,Math.sin(anim*1.8)*.2);}
  if(state==='landing'){const t=THREE.MathUtils.smoothstep(anim,0,3);main.position.lerpVectors(flightStart,anchors[landing],t);main.position.y+=Math.sin(t*Math.PI)*1.3;main.rotation.y=THREE.MathUtils.damp(main.rotation.y,0,2,dt);if(anim>=3){state='perched';visited.add(landing);line.textContent=visited.size===3?'The mountain holds this memory. The journey continues.':landing==='Veil'?'A name unspoken, a presence remembered.':landing==='Branch'?'Even an ancient tree can shelter a new memory.':'For a moment, the watchful mountain rests.';ui();if(visited.size===3)window.dispatchEvent(new CustomEvent('jiuge:chapter-complete',{detail:{chapter:3,nextChapter:4}}));}}
  butterflies.forEach((b,i)=>{const flying=i===0&&(state==='flying'||state==='landing'),amp=flying?.95:.2,freq=flying?30:3;const flap=.18+Math.sin(time*freq+b.userData.phase)*amp;const [l,r]=b.userData.wings;if(l)l.rotation.y=flap;if(r)r.rotation.y=-flap;});markers.forEach((m,i)=>m.scale.setScalar(1+Math.sin(time*2+i)*.2));renderer.domElement.dataset.chapter='3';renderer.domElement.dataset.butterflyState=state;renderer.domElement.dataset.restingPlaces=visited.size;
 }
 return {scene,camera,load,get loaded(){return loaded;},get error(){return error;},enter(){active=true;hud.hidden=false;water.position.y=-22;water.visible=false;scene.add(water);ui();},leave(){active=false;water.visible=true;hud.hidden=true;drag=null;},update,onReturn(fn){q('#mountain-return').onclick=fn;},onContinue(fn){q('#mountain-continue').onclick=fn;}};
}
