import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createAtmosphere} from './atmosphere.js';
import {mountainMist} from './mountain-atmosphere.js';

export function createRitualChapter(renderer){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#a6bcc3');scene.fog=new THREE.FogExp2('#97aeb5',.0075);
 const camera=new THREE.PerspectiveCamera(38,2,.12,1300),atmosphere=createAtmosphere(scene),mist=mountainMist(scene);
 scene.add(new THREE.HemisphereLight(0xc7dce4,0x12242b,1.3));const sun=new THREE.DirectionalLight(0xffedd4,2.9);sun.position.set(-15,45,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:150});sun.shadow.normalBias=.06;scene.add(sun);
 const uniforms={time:{value:0},power:{value:0}},hud=document.createElement('section');hud.id='ritual-ui';hud.hidden=true;hud.innerHTML=`<div class="chapter-label">IV · BENEATH THE SILENT SUN</div><p id="ritual-line" aria-live="polite">Gather where the mountain meets the sky.</p><div class="ritual-meter" role="progressbar" aria-label="Awakening the sun" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i></i></div><div class="ritual-actions"><button id="ritual-approach">Approach the Procession</button><button id="ritual-awaken">Awaken the Sun</button><button id="ritual-hold">Hold to Awaken</button><button id="ritual-reset">Begin Again</button><button id="ritual-continue" hidden>Enter the Quiet River</button><button id="ritual-return">Return to the Mountain</button></div><small id="ritual-hint">Travel closer · Click the dark sun, or hold to awaken it</small>`;document.body.append(hud);
 const q=s=>hud.querySelector(s);let loaded=false,active=false,promise,error,banner,sunPos,queue,route,journey=0,travelling=false,charge=0,autoCharge=false,held=false,completed=false,elapsed=0;
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),look=new THREE.Vector2(),smoothLook=new THREE.Vector2();
 function deform(shader){shader.uniforms.uRitualTime=uniforms.time;shader.uniforms.uRitualPower=uniforms.power;shader.vertexShader='uniform float uRitualTime;uniform float uRitualPower;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nfloat freeCloth=pow(clamp((${banner.userData.clothTop.toFixed(7)}-position.y)/${banner.userData.clothSpan.toFixed(7)},0.,1.),2.);transformed.x+=sin(position.y*17.+uRitualTime*1.25)*freeCloth*(.004+.018*uRitualPower);transformed.z+=cos(position.y*13.+uRitualTime)*freeCloth*(.002+.008*uRitualPower);`);}
 function load(){if(promise)return promise;promise=new GLTFLoader().loadAsync('./models/jiuge_ritual.glb').then(g=>{
  scene.add(g.scene);const processed=new Set();g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of [].concat(o.material)){if(processed.has(m))continue;processed.add(m);m.roughness=Math.max(.75,m.roughness??.8);m.side=THREE.DoubleSide;if(m.map)m.map.anisotropy=4;}}});
  banner=g.scene.getObjectByName('Sun_Phoenix_Banner');if(!banner)throw Error('Missing sun banner');sunPos=g.scene.getObjectByName('Sun_Anchor').getWorldPosition(new THREE.Vector3());queue=g.scene.getObjectByName('Queue_Target').getWorldPosition(new THREE.Vector3());
  banner.geometry.computeBoundingBox();const box=banner.geometry.boundingBox,h=box.max.y-box.min.y;banner.userData.clothTop=box.min.y+h*.64;banner.userData.clothSpan=h*.64;
  // Emission is part of the actual drum surface, not an offset ring mesh.
  banner.material=[].concat(banner.material).map(m=>{const mat=m.clone();mat.onBeforeCompile=shader=>{deform(shader);shader.vertexShader='varying vec3 vDrumPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvDrumPosition=position;');shader.fragmentShader='varying vec3 vDrumPosition;uniform float uRitualPower;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <emissivemap_fragment>',`#include <emissivemap_fragment>
float drumRadius=length((vDrumPosition.xy-vec2(-.0007,.8681))/vec2(.101,.096));
float frontFace=smoothstep(.046,.061,vDrumPosition.z);
float goldenEdge=(exp(-pow((drumRadius-.94)/.085,2.))+.22*exp(-pow((drumRadius-.91)/.17,2.)))*frontFace;
totalEmissiveRadiance+=vec3(.9,.48,.08)*goldenEdge*uRitualPower;`);};mat.customProgramCacheKey=()=> 'ritual-surface-gold-v3';return mat;});if(banner.material.length===1)banner.material=banner.material[0];banner.customDepthMaterial=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking});banner.customDepthMaterial.onBeforeCompile=deform;

  const y=queue.y;route=new THREE.CatmullRomCurve3([new THREE.Vector3(13,16,58),new THREE.Vector3(7,13,36),new THREE.Vector3(-4,y+5,22),new THREE.Vector3(-14,y+3,12),new THREE.Vector3(-24,y+3.5,12),new THREE.Vector3(-27,y+5,19),new THREE.Vector3(-15,y+8,29)],false,'centripetal');
  loaded=true;return true;
 }).catch(e=>{error=e;promise=null;console.error('Chapter IV:',e);return false;});return promise;}
 function awaken(){if(!active||!loaded||completed)return;autoCharge=true;travelling=true;q('#ritual-approach').textContent='Pause the Journey';q('#ritual-awaken').textContent='Awakening…';q('#ritual-awaken').disabled=true;q('#ritual-line').textContent='Let the light carry what words cannot.';}
 function reset(){q('#ritual-continue').hidden=true;journey=0;charge=0;travelling=false;autoCharge=false;held=false;completed=false;elapsed=0;q('#ritual-awaken').disabled=false;q('#ritual-awaken').textContent='Awaken the Sun';q('#ritual-approach').textContent='Approach the Procession';q('#ritual-line').textContent='Gather where the mountain meets the sky.';q('#ritual-hold').disabled=false;q('#ritual-approach').disabled=false;q('#ritual-hint').textContent='Travel closer · Click the dark sun, or hold to awaken it';}
 q('#ritual-approach').onclick=()=>{travelling=!travelling;q('#ritual-approach').textContent=travelling?'Pause the Journey':'Continue the Journey';};q('#ritual-awaken').onclick=awaken;q('#ritual-reset').onclick=reset;
 q('#ritual-hold').addEventListener('pointerdown',e=>{if(completed)return;held=true;travelling=true;q('#ritual-hold').setPointerCapture(e.pointerId);});for(const e of ['pointerup','pointercancel','lostpointercapture'])q('#ritual-hold').addEventListener(e,()=>held=false);addEventListener('blur',()=>held=false);
 renderer.domElement.addEventListener('pointermove',e=>{if(active){const r=renderer.domElement.getBoundingClientRect();look.set((e.clientX-r.left)/r.width*2-1,(e.clientY-r.top)/r.height*2-1);}});
 renderer.domElement.addEventListener('click',e=>{if(!active||!loaded)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(banner,true)[0];if(hit&&hit.point.y>sunPos.y-4)awaken();});
 function update(dt,time){if(!active||!loaded)return;elapsed+=dt;uniforms.time.value=time;atmosphere.update(time);mist.update(time);smoothLook.lerp(look,1-Math.exp(-dt*2));if(travelling)journey=Math.min(1,journey+dt/24);if(held||autoCharge)charge=Math.min(1,charge+dt/11);uniforms.power.value=THREE.MathUtils.smoothstep(charge,0,1);
  camera.aspect=renderer.domElement.clientWidth/renderer.domElement.clientHeight;camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(32))/camera.aspect));camera.updateProjectionMatrix();camera.position.copy(route.getPointAt(journey));camera.position.x+=smoothLook.x*.65;camera.position.y-=smoothLook.y*.4;
  const target=new THREE.Vector3(-1,13,-5);if(journey<.8)target.lerp(queue,THREE.MathUtils.smoothstep(journey,.08,.45));else target.copy(queue).lerp(sunPos,THREE.MathUtils.smoothstep(journey,.8,1)*.65);
  if(journey===1){camera.position.x+=Math.sin(elapsed*.1)*1.4;camera.position.z+=Math.cos(elapsed*.1)*.6;}camera.lookAt(target);
  q('.ritual-meter i').style.width=`${charge*100}%`;q('.ritual-meter').setAttribute('aria-valuenow',Math.round(charge*100));
  if(charge>=1&&journey>=1&&!completed){completed=true;q('#ritual-continue').hidden=false;q('#ritual-line').textContent='The light remembers. One last passage lies ahead.';q('#ritual-hint').textContent='A final river awaits.';q('#ritual-awaken').textContent='The Sun Is Awake';q('#ritual-hold').disabled=true;q('#ritual-approach').textContent='Journey Complete';q('#ritual-approach').disabled=true;window.dispatchEvent(new CustomEvent('jiuge:chapter-complete',{detail:{chapter:4,nextChapter:5}}));}
  renderer.domElement.dataset.chapter='4';renderer.domElement.dataset.ritualJourney=journey.toFixed(3);renderer.domElement.dataset.sunAwakening=charge.toFixed(3);renderer.domElement.dataset.ritualComplete=String(completed);
 }
 return {scene,camera,load,get loaded(){return loaded;},get error(){return error;},enter(){active=true;hud.hidden=false;},leave(){active=false;hud.hidden=true;held=false;},update,onContinue(fn){q('#ritual-continue').onclick=fn;},onReturn(fn){q('#ritual-return').onclick=fn;}};
}
